#Descobrindo o que foi digitado
algo=input('Digite qualquer coisa:')
print(type(algo))
print('O que vc digitou é alfanumérico:',algo.isalnum())
print('O que vc digitou é alfabeto:',algo.isalpha())
print('O que vc digitou é ascii:',algo.isascii())
print('O que vc digitou é digito:',algo.isdigit())
print('O que vc digitou está em minusculas:',algo.islower())
print('O que vc digitou é um decimal:',algo.isdecimal())
print('O que vc digitou é identifier:',algo.isidentifier())
print('O que vc digitou é um número:',algo.isnumeric())
print('O que vc digitou é printável:',algo.isprintable())
print('O que vc digitou é espaço:',algo.isspace())
print('O que vc digitou é title:',algo.istitle())
print('O que vc digitou está em maiusculas:',algo.isupper())
